version: '2.0'
services:
  selenese:
    build:
      context: .
      dockerfile: ./docker/selenese/Dockerfile
    command: run.sh https://google.com chrome
    volumes:
      - ./run.sh:/usr/local/bin/run.sh
      - ./selenese.conf:/etc/selenese.conf
      - ./screenshots/all:/usr/local/share/screenshots/all
      - ./screenshots/fail:/usr/local/share/screenshots/fail
      - ./user-extension.js:/usr/local/share/user-extension.js
      - ./testsuite.html:/usr/local/share/testsuite.html
      - ./junit:/usr/local/share/junit
      - ./test:/usr/local/share/test
    depends_on:
      - hub
  hub:
    build:
      context: .
      dockerfile: ./docker/hub/Dockerfile
    ports:
      - "4444:4444"
  firefox:
    extends: _node
    image: selenium/node-firefox
    depends_on:
      - hub
  chrome:
    extends: _node
    image: selenium/node-chrome
    depends_on:
      - hub
  _node:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
